name: Desktop 构建

on:
  workflow_dispatch:
    inputs:
      reason:
        description: '手动触发构建的原因'
        required: false
        default: '手动测试构建'

permissions:
  contents: read
  actions: read

jobs:
  build-windows:
    runs-on: windows-latest
    name: 构建 Windows 桌面版本

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 JDK 17
        id: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: 构建 Windows 程序
        # packageDistributionForCurrentOS 是 Compose Multiplatform 生成安装包的标准命令
        run: |
          .\gradlew.bat :composeApp:packageDistributionForCurrentOS
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}

      - name: 检查生成目录 (调试用)
        run: |
          dir composeApp\build\compose\binaries\main\

      - name: 上传 EXE 安装包
        uses: actions/upload-artifact@v4
        with:
          name: traclock-windows-installer
          path: composeApp/build/compose/binaries/main/exe/*.exe
          retention-days: 7

      - name: 上传免安装绿色版 (文件夹)
        uses: actions/upload-artifact@v4
        with:
          name: traclock-windows-portable
          path: composeApp/build/compose/binaries/main/app/
          retention-days: 7

  # macOS 和 Linux 暂时保持禁用，如果需要可以改为 true
  build-macos:
    runs-on: macos-latest
    if: false
    steps:
      - uses: actions/checkout@v4
      - name: 设置 JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      - name: 构建 macOS DMG
        run: ./gradlew :composeApp:packageDistributionForCurrentOS
      - name: 上传 DMG
        uses: actions/upload-artifact@v4
        with:
          name: traclock-macos-dmg
          path: composeApp/build/compose/binaries/main/dmg/*.dmg

  build-linux:
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/checkout@v4
      - name: 设置 JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      - name: 构建 Linux DEB
        run: ./gradlew :composeApp:packageDistributionForCurrentOS
      - name: 上传 DEB
        uses: actions/upload-artifact@v4
        with:
          name: traclock-linux-deb
          path: composeApp/build/compose/binaries/main/deb/*.deb
